from pyparsing import Literal


ASSIGN = Literal("=")
NEQ = Literal("!=")
MOD = Literal("%")
MUL = Literal("*")
ADD = Literal("+")
SUB = Literal("-")
DIV = Literal("/")
LT = Literal("<")
LE = Literal("<=")
EQ = Literal("==")
GT = Literal(">")
GE = Literal(">=")
QUESTION = Literal("?")
COLON = Literal(":")
LBRACKET = Literal("[")
RBRACKET = Literal("]")

MOD_ASSIGN = Literal("%=")
MUL_ASSIGN = Literal("*=")
ADD_ASSIGN = Literal("+=")
SUB_ASSIGN = Literal("-=")
DIV_ASSIGN = Literal("/=")
COLON_ASSIGN = Literal(":=")
